### ISSUE TITLE
Getting an error when attempting to use this package with a nami wallet

### ISSUE THREAD

**Issue by GGAlanSmithee** [Asterium-Blockchain/use-cardano-wallet#4]
### Reproduction

1. clone the repo locally
2. build the source code
3. run the example app, found in `./example`
4. click the "connect nami" button
5. Authorize the connection in nami wallet

### Expected result

Wallet is connected

### Actual result

Wallet is not connected, and an error is thrown

### Details

The error that is thrown is this:

```ts
error TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (index.js:311:1)
    at from (index.js:137:1)
    at Buffer.from (index.js:149:1)
    at fromHex (utils.ts:1:54)
    at _callee2$ (index.ts:96:23)
    at tryCatch (index.js:48:1)
    at Generator._invoke (index.js:48:1)
    at Generator.next (index.js:48:1)
    at asyncGeneratorStep (index.js:48:1)
    at _next (index.js:48:1)
```

The error stems from [here](https://github.com/Asterium-Blockchain/use-cardano-wallet/blob/main/src/store/index.ts#L85):

```ts
const [rawAddress] = await api.getUnusedAddresses();
const address = fromHex(rawAddress); // throws the error
```

I am just getting started with web3 on Cardano so there are a lot of concepts that are new to me, but from what I can tell `api.getUnusedAddresses()` returns an empty array. By extension, `rawAddress` is undefined, which is not an acceptable value in `fromHex`.

I guess the issue could be with the CIP 30 web bridge `api` that nami injects, but I have no way to really check that, because I don't know what `getUnusedAddresses` is supposed to return in the context.

**Comment by GGAlanSmithee** [comment]
I see that there was a PR for this, https://github.com/Asterium-Blockchain/use-cardano-wallet/pull/2, but it seems to be closed due to some disagreements of opinions. I will see if I can resurrect and ammend it.

**Comment by GGAlanSmithee** [comment]
I was able to get the reference PR working (as in non breaking) but not sure if correct. I left a comment in the PR if anyone want to pick it up with me.
